# Parametry CNN
CNN_EPOCHS_MRI = 11
BATCH_SIZE_MRI = 32
CNN_INPUT_SHAPE_MRI = (120,120,1)
VALIDATE_RATIO = 0.9   # ilosc w % ktora idzie na zbior testowy ze zbioru temp


#SPRAWDZ TĄ ŚCIEŻKĘ I POPRAW WZGLĘDNĄ
CNN_MODELS_PATH_MRI = "MRI/CNN/MODEL"
CNN_PREDICT_PATH_MRI = "MRI/CNN/PREDICT/PREDICT_DATA"
PICKLE_DATA_ADHD_PATH = "MRI/PICKLE_DATA/ADHDImages.pkl"
PICKLE_DATA_CONTROL_PATH = "MRI/PICKLE_DATA/controlImages.pkl"
GAN_MODELS_PATH = "MRI/GAN/MODEL"