EEG_DATA_PATH = 'EEG'                                                           # Folder z danymi
EEG_SUBFOLDERS = ['ADHD', 'CONTROL']                                                # Wszystkie podfoldery z głównego folderu z danymi
EEG_POS_PHRASE = 'ADHD'                                                             # Fraza zawierająca się w nazwie folderu z grupą chorych pacjentów
EEG_NEG_PHRASE = 'CONTROL'                                                          # Fraza zawierająca się w nazwie folderu z grupą kontrolną
EEG_SIGNAL_FRAME_SIZE = 128                                                         # wielkość pojedyńczej próbki pobieranej z danych elektrody
CNN_MODELS_PATH = './CNN/trained_models'                                            # folder do zapisywania modeli
CNN_POS_LABEL = "ADHD"                                                            # wyjście pozytywne z modelu
CNN_NEG_LABEL = "NO_ADHD"                                                         # wyjście negatywne
CNN_TEST_RATIO = 0.2                                                                # proporcja ilości próbek danych testowych do treningowych 
CNN_INPUT_SHAPE = (19, EEG_SIGNAL_FRAME_SIZE, 1)                                    # 19 - ilość elektrod ; wielkość ramki danych ; 1 - magiczna liczba którą wymaga keras
CNN_EPOCHS = 5                                                                      # Ilość przejść do przodu przez model
CUTOFFS = [(4,8), (13,30), (4,30)]                                                  # Przedziały częstotliwości theta, beta, wszystko
FS = 128                                                                            # Częstotliwośc próbkowania